Add chainId instead of network-url in main route.
oceanprotocol/provider pull request #171
Opened 2021-06-30 07:14 UTC by calina-c

2021-07-01 07:25 UTC, trentmc commented
Ideally this points to a github issue, and the github issue describes the motivation behind doing this change. It can be short.

2021-07-01 07:35 UTC, calina-c commented
> Ideally this points to a github issue, and the github issue describes the motivation behind doing this change. It can be short.

Added in description.

2021-07-01 16:38 UTC, DMats requested changes

2021-07-01 16:38 UTC, DMats commented on deployment/README.md
> +{"computeAddress":null,"chainId":"1","providerAddress":"0xe08A1dAe983BC701D05E492DB80e0144f8f4b909","serviceEndpoints":{"computeDelete":["DELETE","/api/v1/services/compute"],"computeStart":["POST","/
The instructions above this line set `NETWORK_URL: ropsten`. For consistency, change the chainId to 3.

2021-07-01 19:09 UTC, DMats requested changes
I asked a question related to this PR at https://github.com/oceanprotocol/privateissues/issues/21#issuecomment-872409680. I'm hoping to get an answer before approving.

2021-07-06 02:46 UTC, DMats submitted a review, later dismissed

2021-07-06 15:50 UTC, alexcos20 requested changes
If we can store the chain_id at start  and use that value, would be great.


Vector attack:  Somebody will refresh your root endpoint 100.000 times.  this translates to 100k infura requests.  If you have a limited account, then your provider is down

2021-07-07 08:28 UTC, alexcos20 approved these changes

2021-07-07 14:15 UTC, merged