Fix and add some docstrings.
oceanprotocol/provider pull request #431
Opened 2022-04-28 11:35 UTC by calina-c

Closes #349.

2022-04-28 19:52 UTC, DMats requested changes

2022-04-28 19:52 UTC, DMats commented on ocean_provider/routes/decrypt.py
> +            required if dataNftAddress, encryptedDocument and flags parameters missing
I think this could be improved to `transaction id where the document was created or last updated`

2022-04-28 19:52 UTC, DMats commented on ocean_provider/routes/decrypt.py
> +        description: encryption flags,
`encryption and compression flags`

2022-04-28 19:52 UTC, DMats commented on ocean_provider/routes/decrypt.py
> +        description: document hashed used for integrity check,
`hash of the original document used for integrity check`

2022-04-28 19:52 UTC, DMats commented on ocean_provider/utils/accounts.py
> +    Signs message based on the wallet
`Signs the message with the private key of the given Wallet`

2022-04-29 05:10 UTC, calina-c commented on ocean_provider/routes/compute.py
> +        description: One or more of the required attributes are missing or invalid.
added "or invalid" everywhere 👍

2022-04-29 05:11 UTC, calina-c commented on ocean_provider/routes/decrypt.py
> +        description: address of agent requesting decrypt
I think there's not much help in changing it now, but If you want to, we can create an issue to track this.

2022-04-29 10:38 UTC, DMats commented on ocean_provider/routes/decrypt.py
> +        description: address of agent requesting decrypt
That's a good idea. I'll create the issue today.

2022-04-29 10:48 UTC, DMats approved these changes

2022-04-29 14:03 UTC, merged