add pure mutability
oceanprotocol/provider pull request #549
Opened 2022-10-25 16:00 UTC by alexcos20

Changes proposed in this PR:

- 
- 
-

2022-10-25 19:42 UTC, trentmc commented
Which github issue is this for?

2022-10-25 20:36 UTC, alexcos20 commented
added issue now

2022-10-25 23:14 UTC, trentmc requested changes
Thanks for linking to the issue.

This will need a unit test as well.

2022-10-26 04:27 UTC, juanpablovs approved these changes

2022-10-26 06:29 UTC, jfdelgad approved these changes

2022-10-26 08:31 UTC, juanpablovs approved these changes

2022-10-26 08:55 UTC, trentmc approved these changes

2022-10-26 10:02 UTC, merged